### ISSUE TITLE
HPA

### ISSUE THREAD

**Issue by Thar-un** [Sanchit-kumar/Feature-Fusion-Multimodal#1]
Hi, I'm having trouble understanding HPA module 
what is it?
and what is it doing?
will be helpfull if you point me to some resources

**Comment by Sanchit-kumar** [comment]
HPA (Hyper pooling atrous) module is doing multi-scale feature fusion using 4 atrous layers with different dilation rate. Since achieving the same using a higher kernel size is computationally expensive, hence a HPA module with different dilation rate is used.
